buildVersion: '@pom.version@'
apiVersion: v.1.0.0
spring:
  application:
    name: service-b
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      reconnect.backoff.ms: 1000
      retry.backoff.ms: 1000
    consumer:
      group-id: service-b
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      order-events: order-events
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      order-cmd: order-cmd
